---
- name: Install apache2 package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd

- name: Enable and start apache2 daemon
  service:
    name: httpd
    enabled: yes
    state: started
